language: python
python:
  - "2.7"
  - "3.5"

jobs:
  include:
    - stage: build
      script: pip install -r requirements.txt && python -m unittest discover

    - stage: deploy
      script: pip install shipa-ci && shipa-ci.py --app=test-deploy --server=$SHIPASERVER --email=$SHIPAEMAIL --password=$SHIPAPASSWORD --verbose
  
